// Code generated by ent, DO NOT EDIT.

package student

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the student type in the database.
	Label = "student"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLoginAccount holds the string denoting the login_account field in the database.
	FieldLoginAccount = "login_account"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldDateOfBirth holds the string denoting the date_of_birth field in the database.
	FieldDateOfBirth = "date_of_birth"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldUpdatedTime holds the string denoting the updated_time field in the database.
	FieldUpdatedTime = "updated_time"
	// FieldVisibleFlg holds the string denoting the visible_flg field in the database.
	FieldVisibleFlg = "visible_flg"
	// EdgeHymns holds the string denoting the hymns edge name in mutations.
	EdgeHymns = "hymns"
	// Table holds the table name of the student in the database.
	Table = "students"
	// HymnsTable is the table that holds the hymns relation/edge.
	HymnsTable = "hymns"
	// HymnsInverseTable is the table name for the Hymn entity.
	// It exists in this package in order to avoid circular dependency with the "hymn" package.
	HymnsInverseTable = "hymns"
	// HymnsColumn is the table column denoting the hymns relation/edge.
	HymnsColumn = "student_hymns"
)

// Columns holds all SQL columns for student fields.
var Columns = []string{
	FieldID,
	FieldLoginAccount,
	FieldPassword,
	FieldUsername,
	FieldDateOfBirth,
	FieldEmail,
	FieldUpdatedTime,
	FieldVisibleFlg,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Student queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLoginAccount orders the results by the login_account field.
func ByLoginAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginAccount, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByDateOfBirth orders the results by the date_of_birth field.
func ByDateOfBirth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateOfBirth, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByUpdatedTime orders the results by the updated_time field.
func ByUpdatedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedTime, opts...).ToFunc()
}

// ByVisibleFlg orders the results by the visible_flg field.
func ByVisibleFlg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibleFlg, opts...).ToFunc()
}

// ByHymnsCount orders the results by hymns count.
func ByHymnsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHymnsStep(), opts...)
	}
}

// ByHymns orders the results by hymns terms.
func ByHymns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHymnsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newHymnsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HymnsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HymnsTable, HymnsColumn),
	)
}
