// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"newdeal/ent/book"
	"newdeal/ent/chapter"
	"newdeal/ent/phrase"
	"newdeal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChapterUpdate is the builder for updating Chapter entities.
type ChapterUpdate struct {
	config
	hooks    []Hook
	mutation *ChapterMutation
}

// Where appends a list predicates to the ChapterUpdate builder.
func (cu *ChapterUpdate) Where(ps ...predicate.Chapter) *ChapterUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "name" field.
func (cu *ChapterUpdate) SetName(s string) *ChapterUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *ChapterUpdate) SetNillableName(s *string) *ChapterUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetNameJp sets the "name_jp" field.
func (cu *ChapterUpdate) SetNameJp(s string) *ChapterUpdate {
	cu.mutation.SetNameJp(s)
	return cu
}

// SetNillableNameJp sets the "name_jp" field if the given value is not nil.
func (cu *ChapterUpdate) SetNillableNameJp(s *string) *ChapterUpdate {
	if s != nil {
		cu.SetNameJp(*s)
	}
	return cu
}

// SetBookID sets the "book_id" field.
func (cu *ChapterUpdate) SetBookID(i int16) *ChapterUpdate {
	cu.mutation.SetBookID(i)
	return cu
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (cu *ChapterUpdate) SetNillableBookID(i *int16) *ChapterUpdate {
	if i != nil {
		cu.SetBookID(*i)
	}
	return cu
}

// AddToPhraseIDs adds the "to_phrase" edge to the Phrase entity by IDs.
func (cu *ChapterUpdate) AddToPhraseIDs(ids ...int64) *ChapterUpdate {
	cu.mutation.AddToPhraseIDs(ids...)
	return cu
}

// AddToPhrase adds the "to_phrase" edges to the Phrase entity.
func (cu *ChapterUpdate) AddToPhrase(p ...*Phrase) *ChapterUpdate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cu.AddToPhraseIDs(ids...)
}

// SetChapterBookID sets the "chapter_book" edge to the Book entity by ID.
func (cu *ChapterUpdate) SetChapterBookID(id int16) *ChapterUpdate {
	cu.mutation.SetChapterBookID(id)
	return cu
}

// SetChapterBook sets the "chapter_book" edge to the Book entity.
func (cu *ChapterUpdate) SetChapterBook(b *Book) *ChapterUpdate {
	return cu.SetChapterBookID(b.ID)
}

// Mutation returns the ChapterMutation object of the builder.
func (cu *ChapterUpdate) Mutation() *ChapterMutation {
	return cu.mutation
}

// ClearToPhrase clears all "to_phrase" edges to the Phrase entity.
func (cu *ChapterUpdate) ClearToPhrase() *ChapterUpdate {
	cu.mutation.ClearToPhrase()
	return cu
}

// RemoveToPhraseIDs removes the "to_phrase" edge to Phrase entities by IDs.
func (cu *ChapterUpdate) RemoveToPhraseIDs(ids ...int64) *ChapterUpdate {
	cu.mutation.RemoveToPhraseIDs(ids...)
	return cu
}

// RemoveToPhrase removes "to_phrase" edges to Phrase entities.
func (cu *ChapterUpdate) RemoveToPhrase(p ...*Phrase) *ChapterUpdate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cu.RemoveToPhraseIDs(ids...)
}

// ClearChapterBook clears the "chapter_book" edge to the Book entity.
func (cu *ChapterUpdate) ClearChapterBook() *ChapterUpdate {
	cu.mutation.ClearChapterBook()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChapterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChapterUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChapterUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChapterUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChapterUpdate) check() error {
	if cu.mutation.ChapterBookCleared() && len(cu.mutation.ChapterBookIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chapter.chapter_book"`)
	}
	return nil
}

func (cu *ChapterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(chapter.Table, chapter.Columns, sqlgraph.NewFieldSpec(chapter.FieldID, field.TypeInt32))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(chapter.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.NameJp(); ok {
		_spec.SetField(chapter.FieldNameJp, field.TypeString, value)
	}
	if cu.mutation.ToPhraseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chapter.ToPhraseTable,
			Columns: []string{chapter.ToPhraseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedToPhraseIDs(); len(nodes) > 0 && !cu.mutation.ToPhraseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chapter.ToPhraseTable,
			Columns: []string{chapter.ToPhraseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ToPhraseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chapter.ToPhraseTable,
			Columns: []string{chapter.ToPhraseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ChapterBookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.ChapterBookTable,
			Columns: []string{chapter.ChapterBookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt16),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ChapterBookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.ChapterBookTable,
			Columns: []string{chapter.ChapterBookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt16),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chapter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChapterUpdateOne is the builder for updating a single Chapter entity.
type ChapterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChapterMutation
}

// SetName sets the "name" field.
func (cuo *ChapterUpdateOne) SetName(s string) *ChapterUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *ChapterUpdateOne) SetNillableName(s *string) *ChapterUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetNameJp sets the "name_jp" field.
func (cuo *ChapterUpdateOne) SetNameJp(s string) *ChapterUpdateOne {
	cuo.mutation.SetNameJp(s)
	return cuo
}

// SetNillableNameJp sets the "name_jp" field if the given value is not nil.
func (cuo *ChapterUpdateOne) SetNillableNameJp(s *string) *ChapterUpdateOne {
	if s != nil {
		cuo.SetNameJp(*s)
	}
	return cuo
}

// SetBookID sets the "book_id" field.
func (cuo *ChapterUpdateOne) SetBookID(i int16) *ChapterUpdateOne {
	cuo.mutation.SetBookID(i)
	return cuo
}

// SetNillableBookID sets the "book_id" field if the given value is not nil.
func (cuo *ChapterUpdateOne) SetNillableBookID(i *int16) *ChapterUpdateOne {
	if i != nil {
		cuo.SetBookID(*i)
	}
	return cuo
}

// AddToPhraseIDs adds the "to_phrase" edge to the Phrase entity by IDs.
func (cuo *ChapterUpdateOne) AddToPhraseIDs(ids ...int64) *ChapterUpdateOne {
	cuo.mutation.AddToPhraseIDs(ids...)
	return cuo
}

// AddToPhrase adds the "to_phrase" edges to the Phrase entity.
func (cuo *ChapterUpdateOne) AddToPhrase(p ...*Phrase) *ChapterUpdateOne {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cuo.AddToPhraseIDs(ids...)
}

// SetChapterBookID sets the "chapter_book" edge to the Book entity by ID.
func (cuo *ChapterUpdateOne) SetChapterBookID(id int16) *ChapterUpdateOne {
	cuo.mutation.SetChapterBookID(id)
	return cuo
}

// SetChapterBook sets the "chapter_book" edge to the Book entity.
func (cuo *ChapterUpdateOne) SetChapterBook(b *Book) *ChapterUpdateOne {
	return cuo.SetChapterBookID(b.ID)
}

// Mutation returns the ChapterMutation object of the builder.
func (cuo *ChapterUpdateOne) Mutation() *ChapterMutation {
	return cuo.mutation
}

// ClearToPhrase clears all "to_phrase" edges to the Phrase entity.
func (cuo *ChapterUpdateOne) ClearToPhrase() *ChapterUpdateOne {
	cuo.mutation.ClearToPhrase()
	return cuo
}

// RemoveToPhraseIDs removes the "to_phrase" edge to Phrase entities by IDs.
func (cuo *ChapterUpdateOne) RemoveToPhraseIDs(ids ...int64) *ChapterUpdateOne {
	cuo.mutation.RemoveToPhraseIDs(ids...)
	return cuo
}

// RemoveToPhrase removes "to_phrase" edges to Phrase entities.
func (cuo *ChapterUpdateOne) RemoveToPhrase(p ...*Phrase) *ChapterUpdateOne {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return cuo.RemoveToPhraseIDs(ids...)
}

// ClearChapterBook clears the "chapter_book" edge to the Book entity.
func (cuo *ChapterUpdateOne) ClearChapterBook() *ChapterUpdateOne {
	cuo.mutation.ClearChapterBook()
	return cuo
}

// Where appends a list predicates to the ChapterUpdate builder.
func (cuo *ChapterUpdateOne) Where(ps ...predicate.Chapter) *ChapterUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChapterUpdateOne) Select(field string, fields ...string) *ChapterUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chapter entity.
func (cuo *ChapterUpdateOne) Save(ctx context.Context) (*Chapter, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChapterUpdateOne) SaveX(ctx context.Context) *Chapter {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChapterUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChapterUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChapterUpdateOne) check() error {
	if cuo.mutation.ChapterBookCleared() && len(cuo.mutation.ChapterBookIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chapter.chapter_book"`)
	}
	return nil
}

func (cuo *ChapterUpdateOne) sqlSave(ctx context.Context) (_node *Chapter, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chapter.Table, chapter.Columns, sqlgraph.NewFieldSpec(chapter.FieldID, field.TypeInt32))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chapter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chapter.FieldID)
		for _, f := range fields {
			if !chapter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chapter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(chapter.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.NameJp(); ok {
		_spec.SetField(chapter.FieldNameJp, field.TypeString, value)
	}
	if cuo.mutation.ToPhraseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chapter.ToPhraseTable,
			Columns: []string{chapter.ToPhraseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedToPhraseIDs(); len(nodes) > 0 && !cuo.mutation.ToPhraseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chapter.ToPhraseTable,
			Columns: []string{chapter.ToPhraseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ToPhraseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chapter.ToPhraseTable,
			Columns: []string{chapter.ToPhraseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ChapterBookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.ChapterBookTable,
			Columns: []string{chapter.ChapterBookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt16),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ChapterBookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.ChapterBookTable,
			Columns: []string{chapter.ChapterBookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt16),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chapter{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chapter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
