// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"newdeal/ent/phrase"
	"newdeal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PhraseDelete is the builder for deleting a Phrase entity.
type PhraseDelete struct {
	config
	hooks    []Hook
	mutation *PhraseMutation
}

// Where appends a list predicates to the PhraseDelete builder.
func (pd *PhraseDelete) Where(ps ...predicate.Phrase) *PhraseDelete {
	pd.mutation.Where(ps...)
	return pd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pd *PhraseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pd.sqlExec, pd.mutation, pd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pd *PhraseDelete) ExecX(ctx context.Context) int {
	n, err := pd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pd *PhraseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(phrase.Table, sqlgraph.NewFieldSpec(phrase.FieldID, field.TypeInt64))
	if ps := pd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pd.mutation.done = true
	return affected, err
}

// PhraseDeleteOne is the builder for deleting a single Phrase entity.
type PhraseDeleteOne struct {
	pd *PhraseDelete
}

// Where appends a list predicates to the PhraseDelete builder.
func (pdo *PhraseDeleteOne) Where(ps ...predicate.Phrase) *PhraseDeleteOne {
	pdo.pd.mutation.Where(ps...)
	return pdo
}

// Exec executes the deletion query.
func (pdo *PhraseDeleteOne) Exec(ctx context.Context) error {
	n, err := pdo.pd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{phrase.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pdo *PhraseDeleteOne) ExecX(ctx context.Context) {
	if err := pdo.Exec(ctx); err != nil {
		panic(err)
	}
}
