// Code generated by ent, DO NOT EDIT.

package ent

import (
	"newdeal/ent/hymn"
	"newdeal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hymnFields := schema.Hymn{}.Fields()
	_ = hymnFields
	// hymnDescUpdatedUser is the schema descriptor for updated_user field.
	hymnDescUpdatedUser := hymnFields[5].Descriptor()
	// hymn.UpdatedUserValidator is a validator for the "updated_user" field. It is called by the builders before save.
	hymn.UpdatedUserValidator = hymnDescUpdatedUser.Validators[0].(func(int64) error)
}
