// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"newdeal/common"
	"newdeal/ent/hymn"
	"newdeal/ent/role"
	"newdeal/ent/student"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentCreate is the builder for creating a Student entity.
type StudentCreate struct {
	config
	mutation *StudentMutation
	hooks    []Hook
}

// SetLoginAccount sets the "login_account" field.
func (sc *StudentCreate) SetLoginAccount(s string) *StudentCreate {
	sc.mutation.SetLoginAccount(s)
	return sc
}

// SetPassword sets the "password" field.
func (sc *StudentCreate) SetPassword(s string) *StudentCreate {
	sc.mutation.SetPassword(s)
	return sc
}

// SetUsername sets the "username" field.
func (sc *StudentCreate) SetUsername(s string) *StudentCreate {
	sc.mutation.SetUsername(s)
	return sc
}

// SetDateOfBirth sets the "date_of_birth" field.
func (sc *StudentCreate) SetDateOfBirth(c *common.Date) *StudentCreate {
	sc.mutation.SetDateOfBirth(c)
	return sc
}

// SetRoleID sets the "role_id" field.
func (sc *StudentCreate) SetRoleID(i int64) *StudentCreate {
	sc.mutation.SetRoleID(i)
	return sc
}

// SetEmail sets the "email" field.
func (sc *StudentCreate) SetEmail(s string) *StudentCreate {
	sc.mutation.SetEmail(s)
	return sc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (sc *StudentCreate) SetNillableEmail(s *string) *StudentCreate {
	if s != nil {
		sc.SetEmail(*s)
	}
	return sc
}

// SetUpdatedTime sets the "updated_time" field.
func (sc *StudentCreate) SetUpdatedTime(t time.Time) *StudentCreate {
	sc.mutation.SetUpdatedTime(t)
	return sc
}

// SetNillableUpdatedTime sets the "updated_time" field if the given value is not nil.
func (sc *StudentCreate) SetNillableUpdatedTime(t *time.Time) *StudentCreate {
	if t != nil {
		sc.SetUpdatedTime(*t)
	}
	return sc
}

// SetVisibleFlg sets the "visible_flg" field.
func (sc *StudentCreate) SetVisibleFlg(b bool) *StudentCreate {
	sc.mutation.SetVisibleFlg(b)
	return sc
}

// SetID sets the "id" field.
func (sc *StudentCreate) SetID(i int64) *StudentCreate {
	sc.mutation.SetID(i)
	return sc
}

// AddUpdatedHymnIDs adds the "updated_hymns" edge to the Hymn entity by IDs.
func (sc *StudentCreate) AddUpdatedHymnIDs(ids ...int64) *StudentCreate {
	sc.mutation.AddUpdatedHymnIDs(ids...)
	return sc
}

// AddUpdatedHymns adds the "updated_hymns" edges to the Hymn entity.
func (sc *StudentCreate) AddUpdatedHymns(h ...*Hymn) *StudentCreate {
	ids := make([]int64, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return sc.AddUpdatedHymnIDs(ids...)
}

// SetStudentRoleID sets the "student_role" edge to the Role entity by ID.
func (sc *StudentCreate) SetStudentRoleID(id int64) *StudentCreate {
	sc.mutation.SetStudentRoleID(id)
	return sc
}

// SetStudentRole sets the "student_role" edge to the Role entity.
func (sc *StudentCreate) SetStudentRole(r *Role) *StudentCreate {
	return sc.SetStudentRoleID(r.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (sc *StudentCreate) Mutation() *StudentMutation {
	return sc.mutation
}

// Save creates the Student in the database.
func (sc *StudentCreate) Save(ctx context.Context) (*Student, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StudentCreate) SaveX(ctx context.Context) *Student {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StudentCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StudentCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StudentCreate) check() error {
	if _, ok := sc.mutation.LoginAccount(); !ok {
		return &ValidationError{Name: "login_account", err: errors.New(`ent: missing required field "Student.login_account"`)}
	}
	if _, ok := sc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Student.password"`)}
	}
	if _, ok := sc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Student.username"`)}
	}
	if _, ok := sc.mutation.DateOfBirth(); !ok {
		return &ValidationError{Name: "date_of_birth", err: errors.New(`ent: missing required field "Student.date_of_birth"`)}
	}
	if _, ok := sc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "Student.role_id"`)}
	}
	if _, ok := sc.mutation.VisibleFlg(); !ok {
		return &ValidationError{Name: "visible_flg", err: errors.New(`ent: missing required field "Student.visible_flg"`)}
	}
	if len(sc.mutation.StudentRoleIDs()) == 0 {
		return &ValidationError{Name: "student_role", err: errors.New(`ent: missing required edge "Student.student_role"`)}
	}
	return nil
}

func (sc *StudentCreate) sqlSave(ctx context.Context) (*Student, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StudentCreate) createSpec() (*Student, *sqlgraph.CreateSpec) {
	var (
		_node = &Student{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(student.Table, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt64))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.LoginAccount(); ok {
		_spec.SetField(student.FieldLoginAccount, field.TypeString, value)
		_node.LoginAccount = value
	}
	if value, ok := sc.mutation.Password(); ok {
		_spec.SetField(student.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := sc.mutation.Username(); ok {
		_spec.SetField(student.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := sc.mutation.DateOfBirth(); ok {
		_spec.SetField(student.FieldDateOfBirth, field.TypeTime, value)
		_node.DateOfBirth = value
	}
	if value, ok := sc.mutation.Email(); ok {
		_spec.SetField(student.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := sc.mutation.UpdatedTime(); ok {
		_spec.SetField(student.FieldUpdatedTime, field.TypeTime, value)
		_node.UpdatedTime = value
	}
	if value, ok := sc.mutation.VisibleFlg(); ok {
		_spec.SetField(student.FieldVisibleFlg, field.TypeBool, value)
		_node.VisibleFlg = value
	}
	if nodes := sc.mutation.UpdatedHymnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   student.UpdatedHymnsTable,
			Columns: []string{student.UpdatedHymnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hymn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.StudentRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   student.StudentRoleTable,
			Columns: []string{student.StudentRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StudentCreateBulk is the builder for creating many Student entities in bulk.
type StudentCreateBulk struct {
	config
	err      error
	builders []*StudentCreate
}

// Save creates the Student entities in the database.
func (scb *StudentCreateBulk) Save(ctx context.Context) ([]*Student, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Student, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StudentCreateBulk) SaveX(ctx context.Context) []*Student {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StudentCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StudentCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
