// Code generated by ent, DO NOT EDIT.

package role

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the role type in the database.
	Label = "role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVisibleFlg holds the string denoting the visible_flg field in the database.
	FieldVisibleFlg = "visible_flg"
	// EdgeRoled holds the string denoting the roled edge name in mutations.
	EdgeRoled = "roled"
	// EdgeAuth holds the string denoting the auth edge name in mutations.
	EdgeAuth = "auth"
	// Table holds the table name of the role in the database.
	Table = "roles"
	// RoledTable is the table that holds the roled relation/edge.
	RoledTable = "students"
	// RoledInverseTable is the table name for the Student entity.
	// It exists in this package in order to avoid circular dependency with the "student" package.
	RoledInverseTable = "students"
	// RoledColumn is the table column denoting the roled relation/edge.
	RoledColumn = "role_id"
	// AuthTable is the table that holds the auth relation/edge. The primary key declared below.
	AuthTable = "role_auth"
	// AuthInverseTable is the table name for the Auth entity.
	// It exists in this package in order to avoid circular dependency with the "auth" package.
	AuthInverseTable = "authorities"
)

// Columns holds all SQL columns for role fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldVisibleFlg,
}

var (
	// AuthPrimaryKey and AuthColumn2 are the table columns denoting the
	// primary key for the auth relation (M2M).
	AuthPrimaryKey = []string{"role_id", "auth_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Role queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVisibleFlg orders the results by the visible_flg field.
func ByVisibleFlg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibleFlg, opts...).ToFunc()
}

// ByRoledCount orders the results by roled count.
func ByRoledCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoledStep(), opts...)
	}
}

// ByRoled orders the results by roled terms.
func ByRoled(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoledStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuthCount orders the results by auth count.
func ByAuthCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthStep(), opts...)
	}
}

// ByAuth orders the results by auth terms.
func ByAuth(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRoledStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoledInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoledTable, RoledColumn),
	)
}
func newAuthStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, AuthTable, AuthPrimaryKey...),
	)
}
