// Code generated by ent, DO NOT EDIT.

package book

import (
	"newdeal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int16) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int16) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int16) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int16) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int16) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int16) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int16) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int16) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int16) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldName, v))
}

// NameJp applies equality check predicate on the "name_jp" field. It's identical to NameJpEQ.
func NameJp(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldNameJp, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldName, v))
}

// NameJpEQ applies the EQ predicate on the "name_jp" field.
func NameJpEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldEQ(FieldNameJp, v))
}

// NameJpNEQ applies the NEQ predicate on the "name_jp" field.
func NameJpNEQ(v string) predicate.Book {
	return predicate.Book(sql.FieldNEQ(FieldNameJp, v))
}

// NameJpIn applies the In predicate on the "name_jp" field.
func NameJpIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldIn(FieldNameJp, vs...))
}

// NameJpNotIn applies the NotIn predicate on the "name_jp" field.
func NameJpNotIn(vs ...string) predicate.Book {
	return predicate.Book(sql.FieldNotIn(FieldNameJp, vs...))
}

// NameJpGT applies the GT predicate on the "name_jp" field.
func NameJpGT(v string) predicate.Book {
	return predicate.Book(sql.FieldGT(FieldNameJp, v))
}

// NameJpGTE applies the GTE predicate on the "name_jp" field.
func NameJpGTE(v string) predicate.Book {
	return predicate.Book(sql.FieldGTE(FieldNameJp, v))
}

// NameJpLT applies the LT predicate on the "name_jp" field.
func NameJpLT(v string) predicate.Book {
	return predicate.Book(sql.FieldLT(FieldNameJp, v))
}

// NameJpLTE applies the LTE predicate on the "name_jp" field.
func NameJpLTE(v string) predicate.Book {
	return predicate.Book(sql.FieldLTE(FieldNameJp, v))
}

// NameJpContains applies the Contains predicate on the "name_jp" field.
func NameJpContains(v string) predicate.Book {
	return predicate.Book(sql.FieldContains(FieldNameJp, v))
}

// NameJpHasPrefix applies the HasPrefix predicate on the "name_jp" field.
func NameJpHasPrefix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasPrefix(FieldNameJp, v))
}

// NameJpHasSuffix applies the HasSuffix predicate on the "name_jp" field.
func NameJpHasSuffix(v string) predicate.Book {
	return predicate.Book(sql.FieldHasSuffix(FieldNameJp, v))
}

// NameJpEqualFold applies the EqualFold predicate on the "name_jp" field.
func NameJpEqualFold(v string) predicate.Book {
	return predicate.Book(sql.FieldEqualFold(FieldNameJp, v))
}

// NameJpContainsFold applies the ContainsFold predicate on the "name_jp" field.
func NameJpContainsFold(v string) predicate.Book {
	return predicate.Book(sql.FieldContainsFold(FieldNameJp, v))
}

// HasToChapter applies the HasEdge predicate on the "to_chapter" edge.
func HasToChapter() predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ToChapterTable, ToChapterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToChapterWith applies the HasEdge predicate on the "to_chapter" edge with a given conditions (other predicates).
func HasToChapterWith(preds ...predicate.Chapter) predicate.Book {
	return predicate.Book(func(s *sql.Selector) {
		step := newToChapterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Book) predicate.Book {
	return predicate.Book(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Book) predicate.Book {
	return predicate.Book(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Book) predicate.Book {
	return predicate.Book(sql.NotPredicates(p))
}
