// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Chapter is the predicate function for chapter builders.
type Chapter func(*sql.Selector)

// Hymn is the predicate function for hymn builders.
type Hymn func(*sql.Selector)

// HymnsWork is the predicate function for hymnswork builders.
type HymnsWork func(*sql.Selector)

// Phrase is the predicate function for phrase builders.
type Phrase func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)
